version: '1.0'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb_photos
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: IsThereAnybodyGoingToListenToMyStory
      MONGO_INITDB_DATABASE: PhotoManager
  server:
    image: photo_server_amd64
    build:
      context: .
      dockerfile: dockerfile
    container_name: photo_server
    environment:
      - SERVER_PORT=3000
      - SERVER_DATABASE_URL=mongodb://root:IsThereAnybodyGoingToListenToMyStory@mongodb:27017/
      - SERVER_DATABASE_NAME=PhotoManager
      - SERVER_JWT_SECRET=Sittin' in the stand of the sports arena, waiting for the show to begin Red lights, green lights, strawberry wine, a good friend of mine, follows the stars Venus and Mars are alright tonight
      - SERVER_TOKEN_EXPIRATION=1
      - SERVER_REFRESH_TOKEN_EXPIRATION=30
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
      
volumes:
  dbdata6:
